version: '3.8'

services:
  api:
    container_name: netProactiveAX-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
    ports:
      - "${API_PORT}:${API_DOCKER_PORT}"
    env_file:
      - .env

  mongodb:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    container_name: mongodb
    ports:
      - "27018:27017"
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
 
volumes:
  mongo_data:
